### ISSUE TITLE
[Bug] Cannot use cross entropy for multi-class classification

### ISSUE THREAD

**Issue by echuraev** [mlc-ai/relax#160]
Hi @Ubospica and @SiriusNEO! 

Thank you for your hard work on adding training to TVM. It's amazing work! My student (@ndemashov) and I are working on some experiments related to training, and we were not able to run multi-class classifier training with cross entropy loss function.

In this [commit](https://github.com/echuraev/relax/commit/c5c93a5f41584e139afeb86652f53665ddafcbf2), I added a test to trainer with cross-entropy loss function. And if you run this test, then you get the following error:
```
...
E             7: operator()
E                   at /home/echuraev/Workspace/OctoML/relax-training/src/runtime/relax_vm/vm.cc:659
E             6: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
E                   at /home/echuraev/Workspace/OctoML/relax-training/src/runtime/relax_vm/vm.cc:716
E             5: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
E                   at /home/echuraev/Workspace/OctoML/relax-training/src/runtime/relax_vm/vm.cc:808
E             4: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
E                   at /home/echuraev/Workspace/OctoML/relax-training/src/runtime/relax_vm/vm.cc:790
E             3: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
E                   at /home/echuraev/Workspace/OctoML/relax-training/src/runtime/relax_vm/vm.cc:574
E             2: tvm::runtime::PackedFuncObj::CallPacked(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
E                   at /home/echuraev/Workspace/OctoML/relax-training/include/tvm/runtime/packed_func.h:1217
E             1: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<void (*)(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
E                   at /home/echuraev/Workspace/OctoML/relax-training/include/tvm/runtime/packed_func.h:1213
E             0: tvm::runtime::relax_vm::CheckTensorInfo(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
E                   at /home/echuraev/Workspace/OctoML/relax-training/src/runtime/relax_vm/builtin.cc:175
E             File "/home/echuraev/Workspace/OctoML/relax-training/src/runtime/relax_vm/builtin.cc", line 175
E           ValueError: Check failed: (ptr->dl_tensor.ndim == ndim) is false: ErrorContext(fn=loss_adjoint, loc=param[3], param=targets, annotation=R.Tensor((1,), dtype="int32"))  expect Tensor with ndim 1 but get 2
```

Could you please help us to figure out what's wrong with this test? If the test was configured in the correct way, then probably you could suggest to @ndemashov the possible direction for debugging and fixing this issue. Probably he can help you with this task. 

In our experiments, we are using the latest state of `mlc` branch.

**Comment by Ubospica** [comment]
@echuraev Thanks for your interest about our Trainer APIs! 

Some tests on Trainer with the CrossEntropy loss indeed need to be added. As for your test, I think the problem is that our 
 CrossEntropy requires **label** input (e.g. [2,]), instead of **one-hot** input (e.g. [[0, 0, 1, 0, 0],]). So adding a code snippet like

```
def _make_dataset():
    N = 100
    return [
        [
            np.random.uniform(size=(1, 10)).astype(np.float32),
            np.array([2]).astype(np.int32),
        ]
        for _ in range(N)
    ]
```

before `test_execute_cross_entropy` can work.

BTW, please note that Trainer utilities is a brand-new feature, some APIs may change recently for better functionality and UX. You can follow https://github.com/mlc-ai/relax/pull/158 and we'll add more tests later.

**Comment by echuraev** [comment]
@Ubospica Thank you for your reply! Sorry, yesterday was pretty late and I didn't check how the input data is preprocessed before the training. I took the code from your message and the test was passed, thank you!

I think that to make training in TVM more useful, we can add a `categorical_crossentropy` loss function to the TVM. If you are not against of it, I have asked @ndemashov to do that. I think it would be a nice contribution. What do you think?

**Comment by SiriusNEO** [comment]
@echuraev Sure, it will be good if we have more loss functions. If @ndemashov have any problems when developing, we are glad to help!
