### ISSUE TITLE
how to update repo remotely?

### ISSUE THREAD

**Issue by njuhang** [mlc-ai/relax#263]
I use 
git clone --recursive https://github.com/mlc-ai/relax.git
to clone down the repo.
But every time I use "git pull origin", it occurs unmerged paths and so many modified or both modified files. While I didn't modify anything. 
So I want to know how to update code on my local machine?

**Comment by yzh119** [comment]
That's not your fault, the TVM-Unity branch or the relax project is frequently rebased on TVM mainline.
To pull the updates, you can try
```python
git pull origin mlc --rebase
git submodule update --init --recursive
```

**Comment by njuhang** [comment]
Roger that, thanks a lot
