### ISSUE TITLE
[Bug] dlight decode-gemv generating incorrect schedule

### ISSUE THREAD

**Issue by psrivas2** [mlc-ai/relax#267]
the unit test [test_decode_gemv_4](https://github.com/mlc-ai/relax/blob/mlc/tests/python/dlight/test_gpu_decode_gemv.py#L212) in dlight branch fails to build if I try to compile it using `tvm.build(mod, target)`  at the end of the test case. 

It throws the error:
`
ValueError: Check failed: n_deepest_reduction_loops == reduction_loops.size() (0 vs. 1) : Cross-thread reduction requires all the reduction-related loops to be the deepest among all statements outside the desired block. However, block matmul needs cross-thread reduction, while the reduction-related loops outside of it are not the deepest statements, which violates the condition.
`

cc @zxybazh

**Comment by zxybazh** [comment]
Here's a reproducible script https://gist.github.com/zxybazh/39d1bc9722bdbe30769f9efd4075c9cf

**Comment by zxybazh** [comment]
CC: @spectrometerHBH @junrushao would you please confirm if this check failure is expected?

**Comment by MasterJH5574** [comment]
https://github.com/apache/tvm/pull/15340 fixes this I think.
