### ISSUE TITLE
[Bug] "Please make sure you have the correct access rights" when cloning git@github.com:mlc-ai/relax.git

### ISSUE THREAD

**Issue by flatsiedatsie** [mlc-ai/relax#310]
I'm trying to create a WASM model to run in the browser, and following the steps to do so in the documentation.

I am now at the "install TVM" step, following the "build from source" instructions on [this page](https://llm.mlc.ai/docs/install/tvm.html).

At the step `git clone --recursive git@github.com:mlc-ai/relax.git tvm-unity && cd tvm-unity` I get a permission issue?

### Expected behavior

I expected the git repo to be cloned

### Actual behavior

I could not clone the repo because of a permission issue

### Environment

Mac OS Monterey on Macbook Pro M1

### Steps to reproduce

Follow the [steps](https://llm.mlc.ai/docs/deploy/javascript.html)

### Triage

Please refer to the list of label tags [here](https://github.com/apache/tvm/wiki/Issue-Triage-Labels) to find the relevant tags and add them below in a bullet format (example below).

* needs-triage

Log details:
```
#                                                                                                                                   
# To activate this environment, use
#
#     $ conda activate tvm-build-venv
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) ~/Downloads/ems$ conda activate tvm-build-venv
(tvm-build-venv) ~/Downloads/ems$ git clone --recursive git@github.com:mlc-ai/relax.git tvm-unity && cd tvm-unity
Cloning into 'tvm-unity'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(tvm-build-venv) ~/Downloads/ems$ rm -rf build && mkdir build && cd build
(tvm-build-venv) ~/Downloads/ems/build$ git clone --recursive git@github.com:mlc-ai/relax.git tvm-unity && cd tvm-unity
Cloning into 'tvm-unity'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(tvm-build-venv) ~/Downloads/ems/build$ 


```

**Comment by CharlieFRuan** [comment]
You can change it to
`git clone --recursive https://github.com/mlc-ai/relax.git tvm-unity`
