### ISSUE TITLE
[Bug] tvmRetValueToJava in jni_helper_func.h missing kTVMArgBool case

### ISSUE THREAD

**Issue by yuxuanchiadm** [mlc-ai/relax#324]
### Expected behavior

No crash

### Actual behavior

mlc-llm/3rdparty/tvm/jvm/native/src/main/native/jni_helper_func.h:211: Do NOT know how to handle return type code 15

Simple fix for the issue:
```diff
   switch (tcode) {
     case kDLUInt:
     case kDLInt:
+    case kTVMArgBool:
       return newTVMValueLong(env, static_cast<jlong>(value.v_int64));
     case kDLFloat:
       return newTVMValueDouble(env, static_cast<jdouble>(value.v_float64));
```

### Environment

Android

### Steps to reproduce

```
git clone --recursive https://github.com/mlc-ai/mlc-llm.git
cd mlc-llm/android/MLCChat
mlc_llm package
```
Then build and run android app in Android Studio

### Triage

* needs-triage

**Comment by MasterJH5574** [comment]
Thank you @yuxuanchiadm so much. We've applied the fix you suggested in the latest commit.
